---
name: nexe-test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - ubuntu-20.04,
          - windows-2019
        node:
          - 12
          - 14
          - 15
    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install Dependencies
        run: npm ci
      - name: Test
        run: npm run test -- --reporters=mocha-github-actions-reporter
